import { StyleSheet } from "react-native";

export default StyleSheet.create({
  root: { flex: 1, backgroundColor: "#F8FAFC" },
  header: { backgroundColor: "#0F172A" },
  safeArea: { flex: 1, backgroundColor: "#F8FAFC" },
  screen: { padding: 20 },
  title: { fontSize: 32, fontWeight: "800", color: "#0F172A" },
  subtitle: { fontSize: 16, color: "#475569", marginBottom: 20 },
  card: {
    borderRadius: 22,
    backgroundColor: "#FFFFFF",
    padding: 22,
    marginBottom: 18,
    elevation: 5,
  },
  cardAlt: { backgroundColor: "#FEF3C7" },
  cardLabel: { fontSize: 16, color: "#475569" },
  cardValue: { fontSize: 44, fontWeight: "800" },
  cardNote: { marginTop: 10, color: "#64748B" },
  button: {
    backgroundColor: "#0284C7",
    borderRadius: 18,
    padding: 16,
    alignItems: "center",
  },
  buttonSecondary: { backgroundColor: "#0F172A" },
  buttonText: { color: "#FFF", fontWeight: "700" },
  permissionContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#0F172A",
  },
  permissionText: { color: "#FFF", marginBottom: 20 },
  cameraScreen: { flex: 1 },
  camera: { flex: 1 },
  overlay: {
    position: "absolute",
    bottom: 24,
    left: 16,
    right: 16,
    backgroundColor: "rgba(15, 23, 42, 0.8)",
    padding: 18,
    borderRadius: 22,
  },
  overlayTitle: { color: "#7CFF58", fontWeight: "800" },
  overlayText: { color: "#FFF", fontSize: 18 },
  overlayNote: { color: "#CBD5E1", fontSize: 12 },
});
